# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# POSTGRES_USER: gonzalezj       --->>> su apellido más la primera letra de su nombre
# POSTGRES_PASSWORD: Jesus556    --->>> una clave que ud. elija
# POSTGRES_DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 

version: '1.1'

services:

  db-postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: GonzalezP
      POSTGRES_PASSWORD: paomar11
      POSTGRES_DB: Prueba

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: Prueba
      MYSQL_USER: GonzalezP
      MYSQL_PASSWORD: paomar11
      MYSQL_ROOT_PASSWORD: paomar11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db-mysql
      MYSQL_ROOT_PASSWORD: paomar11
